// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHKorHE8tHX7X97tDowfeQfOZI47clA_w',
    appId: '1:390211285822:web:8260ea00f9bf05e0c8b26f',
    messagingSenderId: '390211285822',
    projectId: 'webtech-41802024-finals',
    authDomain: 'webtech-41802024-finals.firebaseapp.com',
    storageBucket: 'webtech-41802024-finals.appspot.com',
    measurementId: 'G-QEZHJCKE7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQYbkp7yjfeoFB4V-N9sjDh42f2O827gk',
    appId: '1:390211285822:android:c77f8b6d8e7eb2d9c8b26f',
    messagingSenderId: '390211285822',
    projectId: 'webtech-41802024-finals',
    storageBucket: 'webtech-41802024-finals.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh4tNB1aZtVBWVWjWfms9bgmTHw6pdAlY',
    appId: '1:390211285822:ios:b02e2613a2b8b3c2c8b26f',
    messagingSenderId: '390211285822',
    projectId: 'webtech-41802024-finals',
    storageBucket: 'webtech-41802024-finals.appspot.com',
    iosClientId: '390211285822-lic45fecmidjhtpqsu8bo4ahfactsbu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalproj41802024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh4tNB1aZtVBWVWjWfms9bgmTHw6pdAlY',
    appId: '1:390211285822:ios:b02e2613a2b8b3c2c8b26f',
    messagingSenderId: '390211285822',
    projectId: 'webtech-41802024-finals',
    storageBucket: 'webtech-41802024-finals.appspot.com',
    iosClientId: '390211285822-lic45fecmidjhtpqsu8bo4ahfactsbu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalproj41802024',
  );
}
